In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("new_credit_risk_dataset.csv")

In [ ]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,1230.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,50.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,10.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,40.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,80.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [ ]:
df['person_emp_length'] = df['person_emp_length']/10
df['person_emp_length'].head()

0    123.0
1      5.0
2      1.0
3      4.0
4      8.0
Name: person_emp_length, dtype: float64

In [ ]:
df['person_income'].value_counts().sort_index()

person_income
4000       1
4080       1
4200       2
4800       3
4888       1
          ..
1440000    1
1782000    1
1900000    1
2039784    1
6000000    1
Name: count, Length: 4295, dtype: int64

In [ ]:
df = df[df['person_emp_length'] != 123]

In [ ]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [ ]:
df['loan_int_rate'] = df['loan_int_rate'].fillna(df['loan_int_rate'].median())
df['person_emp_length']  = df['person_emp_length'].fillna(df['person_emp_length'].median())

/tmp/ipykernel_740/3393239794.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loan_int_rate'] = df['loan_int_rate'].fillna(df['loan_int_rate'].median())
/tmp/ipykernel_740/3393239794.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['person_emp_length']  = df['person_emp_length'].fillna(df['person_emp_length'].median())

In [ ]:
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [ ]:
df['loan_to_income'] = df['loan_amnt']/df['person_income']

In [ ]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_to_income
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.104167
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.572917
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.534351
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.643382
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2,0.252525

In [ ]:
df.info

<bound method DataFrame.info of        person_age  person_income person_home_ownership  person_emp_length  \
1              21           9600                   OWN                5.0
2              25           9600              MORTGAGE                1.0
3              23          65500                  RENT                4.0
4              24          54400                  RENT                8.0
5              21           9900                   OWN                2.0
...           ...            ...                   ...                ...
32576          57          53000              MORTGAGE                1.0
32577          54         120000              MORTGAGE                4.0
32578          65          76000                  RENT                3.0
32579          56         150000              MORTGAGE                5.0
32580          66          42000                  RENT                2.0

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
1            EDUCATION          B       1000          11.14            0
2              MEDICAL          C       5500          12.87            1
3              MEDICAL          C      35000          15.23            1
4              MEDICAL          C      35000          14.27            1
5              VENTURE          A       2500           7.14            1
...                ...        ...        ...            ...          ...
32576         PERSONAL          C       5800          13.16            0
32577         PERSONAL          A      17625           7.49            0
32578  HOMEIMPROVEMENT          B      35000          10.99            1
32579         PERSONAL          B      15000          11.48            0
32580          MEDICAL          B       6475           9.99            0

       loan_percent_income cb_person_default_on_file  \
1                     0.10                         N
2                     0.57                         N
3                     0.53                         N
4                     0.55                         Y
5                     0.25                         N
...                    ...                       ...
32576                 0.11                         N
32577                 0.15                         N
32578                 0.46                         N
32579                 0.10                         N
32580                 0.15                         N

       cb_person_cred_hist_length  loan_to_income
1                               2        0.104167
2                               3        0.572917
3                               2        0.534351
4                               4        0.643382
5                               2        0.252525
...                           ...             ...
32576                          30        0.109434
32577                          19        0.146875
32578                          28        0.460526
32579                          26        0.100000
32580                          30        0.154167

[32579 rows x 13 columns]>

In [ ]:
def employment_category(x):
    if x <= 2:
        return 'New'
    elif x <= 5:
        return 'Early/Mid'
    elif x <= 10:
        return 'Experienced'
    else:
        return 'Highly Experienced'

df['employment_category'] = df['person_emp_length'].apply(employment_category)

In [ ]:
bins = [0, 25, 35, 45, 55, float('inf')]
labels = ['<25', '25-35', '35-45', '45-55', '>55']
df['age_band'] = pd.cut(
    df['person_age'],
    bins = bins,
    labels = labels
)

In [ ]:
bins = [0, 8, 12, 16, 20, float('inf')]
labels = ['<8%', '8-12%', '12-16%', '16-20%', '>20%']
df['interest_rate_band'] = pd.cut(
    df['loan_int_rate'],
    bins = bins,
    labels = labels
)

In [ ]:
//Analysis

In [ ]:
df['person_income'].describe()

count    3.257900e+04
mean     6.607120e+04
std      6.198108e+04
min      4.000000e+03
25%      3.850000e+04
50%      5.500000e+04
75%      7.920000e+04
max      6.000000e+06
Name: person_income, dtype: float64

In [ ]:
df['person_income'].quantile(
    [0, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1]
)

0.00       4000.0
0.10      28588.8
0.25      38500.0
0.50      55000.0
0.75      79200.0
0.90     110004.0
0.95     138000.0
0.99     225220.0
1.00    6000000.0
Name: person_income, dtype: float64

In [ ]:
bins = [0, 38500, 55000, 79200, float('inf')]
labels = [
    'Low Income',
    'Lower-Middle Income',
    'Upper-Middle Income',
    'High Income'
]
df['income_band'] = pd.cut(
    df['person_income'],
    bins = bins,
    labels = labels
)

In [ ]:
df['income_band'].value_counts()

income_band
Lower-Middle Income    8231
Low Income             8152
High Income            8142
Upper-Middle Income    8054
Name: count, dtype: int64

In [ ]:
df['age_band'].value_counts()

age_band
<25      15350
25-35    13763
35-45     2814
45-55      513
>55        139
Name: count, dtype: int64

In [ ]:
df['interest_rate_band'].value_counts()

interest_rate_band
8-12%     13475
12-16%     9373
<8%        7958
16-20%     1699
>20%         74
Name: count, dtype: int64

In [ ]:
df['employment_category'].value_counts()

employment_category
New                   10869
Early/Mid             10171
Experienced            8612
Highly Experienced     2927
Name: count, dtype: int64

In [ ]:
income_default = (
    df.groupby('income_band')['loan_status']
      .agg(['count', 'mean'])
      .reset_index()
)

income_default['default_rate'] = income_default['mean'] * 100

income_default

/tmp/ipykernel_740/3446366343.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('income_band')['loan_status']

           income_band  count      mean  default_rate
0           Low Income   8152  0.396958     39.695780
1  Lower-Middle Income   8231  0.213218     21.321832
2  Upper-Middle Income   8054  0.170598     17.059846
3          High Income   8142  0.091132      9.113240

In [ ]:
df['income_band'].value_counts()
df.groupby('income_band')['loan_status'].mean() * 100

/tmp/ipykernel_740/1768686279.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('income_band')['loan_status'].mean() * 100

income_band
Low Income             39.695780
Lower-Middle Income    21.321832
Upper-Middle Income    17.059846
High Income             9.113240
Name: loan_status, dtype: float64

In [ ]:


df['age_band'].value_counts()
df.groupby('age_band')['loan_status'].mean() * 100

/tmp/ipykernel_740/3227488784.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_band')['loan_status'].mean() * 100

age_band
<25      23.022801
25-35    20.678631
35-45    20.717839
45-55    21.832359
>55      23.021583
Name: loan_status, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('loan_status', axis=1)
y = df['loan_status']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Encoding Categorical features

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
categorical_cols = X.select_dtypes(include=['object', 'category']).columns
numeric_cols = X.select_dtypes(exclude=['object', 'category']).columns

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.pipeline import Pipeline
# Logistic Regression pipeline
lr_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(max_iter=1000))
])

In [ ]:
# Hyperparameters to search
param_grid = {
    'model__C': [0.001, 0.01, 0.1, 1, 10, 100],
    'model__solver': ['liblinear', 'lbfgs'],
    'model__class_weight': [None, 'balanced']
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
# Randomized Search
lr_random = RandomizedSearchCV(
    estimator=lr_pipeline,
    param_distributions=param_grid,
    n_iter=10,
    cv=5,
    scoring='f1',
    random_state=42,
    n_jobs=-1
)

In [ ]:
# Train
lr_random.fit(X_train, y_train)

print("Best Parameters:", lr_random.best_params_)
print("Best CV F1 Score:", lr_random.best_score_)

Best Parameters: {'model__solver': 'lbfgs', 'model__class_weight': None, 'model__C': 100}
Best CV F1 Score: 0.6628684975934852

In [ ]:
from sklearn.metrics import classification_report

# Predictions on test data
y_pred = lr_random.predict(X_test)

# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      5095
           1       0.76      0.56      0.64      1421

    accuracy                           0.86      6516
   macro avg       0.82      0.75      0.78      6516
weighted avg       0.86      0.86      0.86      6516

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(random_state=42, n_jobs=-1))
])

rf_params = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [10, 20, None],
    'model__min_samples_split': [2, 5],
    'model__class_weight': [None, 'balanced']
}

rf_random = RandomizedSearchCV(
    rf_pipeline,
    param_distributions=rf_params,
    n_iter=8,
    cv=3,
    scoring='f1',
    random_state=42,
    n_jobs=-1
)

rf_random.fit(X_train, y_train)

print("Best Parameters:", rf_random.best_params_)
print("Best CV F1 Score:", rf_random.best_score_)

Best Parameters: {'model__n_estimators': 200, 'model__min_samples_split': 2, 'model__max_depth': None, 'model__class_weight': None}
Best CV F1 Score: 0.8211434120408537

In [ ]:
from sklearn.metrics import classification_report

y_pred_rf = rf_random.predict(X_test)

print("Random Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      5095
           1       0.96      0.71      0.81      1421

    accuracy                           0.93      6516
   macro avg       0.94      0.85      0.88      6516
weighted avg       0.93      0.93      0.93      6516

In [ ]:
!pip install xgboost -q

In [ ]:
from xgboost import XGBClassifier

xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(
        random_state=42,
        eval_metric='logloss',
        n_jobs=-1
    ))
])

xgb_params = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [3, 5, 7],
    'model__learning_rate': [0.05, 0.1],
    'model__subsample': [0.8, 1.0],
    'model__colsample_bytree': [0.8, 1.0]
}

xgb_random = RandomizedSearchCV(
    xgb_pipeline,
    param_distributions=xgb_params,
    n_iter=8,
    cv=3,
    scoring='f1',
    random_state=42,
    n_jobs=-1
)

xgb_random.fit(X_train, y_train)

print("Best Parameters:", xgb_random.best_params_)
print("Best CV F1 Score:", xgb_random.best_score_)

Best Parameters: {'model__subsample': 1.0, 'model__n_estimators': 200, 'model__max_depth': 5, 'model__learning_rate': 0.1, 'model__colsample_bytree': 0.8}
Best CV F1 Score: 0.8320114691882581

In [ ]:
y_pred_xgb = xgb_random.predict(X_test)

print("XGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))

XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5095
           1       0.97      0.72      0.83      1421

    accuracy                           0.94      6516
   macro avg       0.95      0.86      0.89      6516
weighted avg       0.94      0.94      0.93      6516